spring:
  datasource:
    url: jdbc:mysql://localhost:3306/movie?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
server:
  port: 80
logging:
  level:
    root: DEBUG
